spring:
  freemarker:
    cache: true

  datasource:
    url: jdbc:mysql://localhost:3306/prod_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  redis:
    cluster:
      max-redirects: 10
      nodes: localhost:7000,localhost:7001,localhost:7002,localhost:7003,localhost:7004,localhost:7005,localhost:7006,localhost:7007,localhost:7008,localhost:7009

logging:
  file: myproject.log
  level:
    com.company.project.springbootproject: info