spring:
  freemarker:
    cache: false

  datasource:
    url: jdbc:mysql://localhost:3306/test_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: 123456

  redis:
    cluster:
      max-redirects: 10
      nodes: localhost:7000,localhost:7001,localhost:7002,localhost:7003,localhost:7004,localhost:7005,localhost:7006,localhost:7007,localhost:7008,localhost:7009

logging:
  path: ./logs
  level:
    root: info
    com.company.project.springbootproject.mapper: trace
